// data.js - pusat data aplikasi Input Nilai ASAS Genap NAFA
// Edit data guru, mapel, kelas, siswa, dan pengampu di file ini saja.
(function(){
  const SMP_DATA = {
        kepalaJabatan: "Kepala SMP Islam Nailul Falaah",
        kepalaNama: "Ahmad Ulin Nuha, Lc.",
        guru: [
          "Ahmad Taufiqurrohman",
          "Ahmad Ulin Nuha, Lc.",
          "Alma Naimatul Miladiah, S.Pd, Gr.",
          "Anisatul Jannah Mulyono, S.Pd, Gr",
          "Arby Zulkifli, S.Pd, Gr.",
          "Arief Rahman Hakim, S.Pd, Gr.",
          "Arsa Rizky Imanda, S.Pd.",
          "Azza Latifatus Zamairoh, S.Pd, Gr.",
          "Bambang Triawan Pamungkas, S.Pd.",
          "Dany Maulana Rizky, S.Pd, Gr.",
          "Denata Novenda Afgenesya, S.Pd, Gr.",
          "Dwi Wulandari, S.Pd, Gr.",
          "Ferri Kurniawan, S.Pd.",
          "Fitrotun Nisa, S.Pd.",
          "Jalilah Al Khasanah, S.Pd.",
          "Marwah Junaedi, M.Pd.",
          "Mohammad Abdul Mukhid, S.Si, Gr.",
          "Moreno Figo Ariyansyah Wibowo, S.Pd.",
          "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
          "Nur Amalia Maurie Husna, S.Pd, Gr.",
          "Nushah Agita Widayanti, S.Pd, Gr.",
          "Peni, S.Pd, Gr.",
          "Rizka Amilia Rosa S.E.",
          "Rosita Eka Mardiana, S.Pd, Gr.",
          "Tiagatus Luqman Widyadhana, S.Pd.",
          "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
          "Ummi Rihana, S.Pd.",
          "Wulan Aulia Al Azhar, S.Pd.",
          "Zihrul Fauzi, S.Pd, Gr.",
        ],
        mapel: [
          "BAHASA DAERAH",
          "BAHASA INDONESIA",
          "BAHASA INGGRIS",
          "INFORMATIKA",
          "IPA",
          "IPS",
          "MATEMATIKA",
          "PAI",
          "PJOK",
          "PKN",
          "SENI BUDAYA",
        ],
        kelas: ["7A", "7B", "7C", "7D", "8A", "8B", "8C", "8D", "8E"],
        siswa: {
          "7A": [
            "Aisyah Aqiila Najibah",
            "Aisyah Wijayanti Candradinata",
            "Ayunda Tsabita",
            "Dhohwah Sholicha",
            "Dzahabiyah Mutiara Angin",
            "Hanna Gelbina Ulya",
            "Luluk Yulistiani",
            "Mahira Hasna Kamila",
            "Mayla Ghumaishah Majid",
            "Nadhifa Adinda Zahra",
            "Naura Ajna Fitria S.",
            "Nuriyatul Kamilla",
            "Qorylaila Ramadhani",
            "Rifka Anaya Nikmatul Azizah",
            "Robihah",
            "Robiihatur Roihaanah Lubis",
            "Shabrina Aqila Adzra R",
            "Shofiya Salsabila Q.A.S",
            "Syofia Khoirun Nissa",
            "Uzla Khoiris Sabila",
            "Zahira Jauza Salim",
          ],
          "8A": [
            "Amira Sani Nadifa Qolbi",
            "Anisa Fadia Karim",
            "Aqilah Annadhifah",
            "Ariana Desta Janati",
            "Auliyah Fisagina Mulianto",
            "Azka Ghoniyah Permatasari",
            "Azzahra Maharani",
            "Dzihniyyah Ramadhani",
            "Fannisa Rehana",
            "Fira Nadya Chalista",
            "Indah Puspa Ramadhani",
            "Janneta Hiyal Ma'wa",
            "Kanaya Kenzie Ramadhani",
            "Mar Atus Sholikha",
            "Najma Maulida Rahma",
            "Nasha Nafisha Setiawati",
            "Neisya Oktavia Rahayu",
            "Nirvana Mufidatus Shifa",
            "Rofifah Maimunah",
            "Syifana Maulida",
            "Vania Raihana Sakhi",
            "Zivana Nayra Dewi",
          ],
          "7B": [
            "Afizah Khaliqa Putri Azzahra",
            "Alexsha Candra Dewi Kirana",
            "Aurani Wahyu Fitria",
            "Diyanah Lathifah",
            "Durroh Syaima Faiha",
            "Gefanda Makayla Zabrina",
            "Ghea Alya Azzilia",
            "Istiana Nur Fadilah",
            "Jaziilah",
            "Maulidia Zahrotun Nisa'",
            "Nabila Ainurrohmah",
            "Nadalia Putrina Shifa",
            "Nafiska Akasya Pusponegoro",
            "Nailah Monic Nur Aisyah",
            "Najwa Narayya Ruditya Ramadhani",
            "Qisya Auni Raqilla",
            "Rafidah Bilqiis Firzanah",
            "Roghdah",
            "Shofroul Lailiyah",
            "Sumayyah",
            "Talita Salsabila Nadhifa",
            "Tsurroyyah",
            "Yulia Az Zahra Afika",
            "Zahirah Nur Hasna",
          ],
          "8B": [
            "Adelia Cahyatusania",
            "Amilia Rahmawati Dewi",
            "Anandhita Shofyana Lathifah",
            "Andini Puspita Sari",
            "Arini Zalzabila Al Firdaus",
            "Aryani Aqila Maulida",
            "Azza Syareyfa Ramadhan Haidar",
            "Azzah Zhahirah Puthree Khoiri",
            "Eka Oktavia",
            "Elsya Dwi Olivia",
            "Erinna Rifdah Sarwahita",
            "Himayah Ilmi Zulfana",
            "Kayla Novirza Aisyah",
            "Khorida Aulia",
            "Lintang Wahyu Nastiti",
            "Nafis Salma Afifah",
            "Queena Bilqis Sharitry Fiaditarica",
            "Siti Nur Aisyah",
            "Tajul A'liyatul Furqonia",
            "Widia Zahira Putri",
          ],
          "7C": [
            "Abizar Baiqaki Iswanto",
            "Ahmad Hirzul Fahmil Akbar",
            "Alif Al Khusainul Wafi",
            "Arfan Ma’ruf",
            "Aryasatya Ghafar Ahmad",
            "Diego Alfahru Suryanto",
            "Dimas Farizky Prayoga",
            "M. Irfan Azmi",
            "M. Rui Fathir Al Fajri",
            "Moch. Yardan Habibillah U",
            "Muhammad Faza Fauzan",
            "Muhammad Syahrul F",
            "Muhammad Zaidan Falahi A",
            "Nasrulloh Al Fattah",
            "Naufal Dary Mahardika",
            "Rafka Maulana Yusuf",
            "Vas Indra Dewa",
            "Zahid",
            "Zhafran Ahmad Al Ghifary",
          ],
          "8C": [
            "Andini Anja Maulydyah",
            "Anindya Qothrun Nada",
            "Asyfi Lailatul Fitriyah",
            "Audy Anjani",
            "Aulia Zahra Tsabitha",
            "Belva Fitria Azmi",
            "Dini Kamiliyah Azizah",
            "Fahima Sa'ya",
            "Faiha Qonita Ayunda Maharani",
            "Feby Maulida Azahra",
            "Hikmah Maulidya Zahrotul Muniroh",
            "Labitta Luthfiatunnisa",
            "Laili Asyifani",
            "Mubarikatul Rizqia",
            "Najah Ramadhani",
            "Naura Keisha Zahra",
            "Nayrazahrotus Sifa'ul Qolbi",
            "Salafa Khodijah Azkiya' Mujit",
            "Syaima Syahla Syabiyyah",
            "Syifa Ayyatul Husna",
            "Syifana Aulia Nugraha",
            "Thooi'ah",
            "Ulya Syauqia Iftinan Rofiqoh",
          ],
          "7D": [
            "Achmad Saqoful Iman",
            "Ahmad Akbar Maulana",
            "Arsa Adibrata",
            "Catur Indra Paramarta",
            "Daffaa",
            "Fatihur Rijal Al Amin",
            "Ibrahim Marzein Iantida",
            "Iqbal Dhian Fikri Ramadani",
            "M. Fauzan Ar Rifqi",
            "Moch. Ezar Ananda P",
            "Mohamad Hanif Ridho Ramadhan",
            "Mohammad Salman Al Farizy",
            "Muhammad Fikri Haikal",
            "Muhammad Miqdan Adli",
            "Muhammad Zain Alif Asshidiq",
            "Sa'dii",
            "Salman Za'imul Umam",
            "Syarifuddin Nur",
            "Zainuddiin",
          ],
          "8D": [
            "Achmad Jagad Rizqullah",
            "Ahmad Naufal Abdillah",
            "Ahmad Raffi Baihaqi",
            "Ahmad Zaky Abyun Syah",
            "Al-Bara Fariza Zain Oktaviano",
            "Alfarisi Wahyu Pratama",
            "Arjuna Abqary Rafasya",
            "Muhammad Azam Mahardika",
            "Muhammad Busthomi",
            "Muhammad Syaifi",
            "Muhammad Syauqi Abdulloh",
            "Muhammad Bahy Abdillah Setiawan",
            "Raditya Keanu Zafier",
            "Rizky Andi Lira Alghozy",
            "Sheva Maulana",
            "Sholihiin",
            "Suruur Roziqin",
            "Wahyu Joyodiningrat",
          ],
          "8E": [
            "Abdulloh Qobus Bilbar",
            "Achmad Nizam Alfarizy",
            "Achmad Wildan Lubis",
            "Ahmad Sufyaan",
            "Alfian Risqi Rahmadan",
            "Bagas Satria Kusuma",
            "Brahman Ahmad Syailendra Hamza",
            "Ega Atilah Ilhamsyah",
            "Erwin Kusuma Pratama",
            "Muhammad Khoirul Huda Hermansyah",
            "Moh. Muammar Kadafi",
            "Muchammad Najmudin Nurillah",
            "M. Nizar Zahir Alamsyah",
            "Moch Rizki Arrival Radita",
            "Syabil Jabir Azzam",
            "Wahyu Nurul Fauzan",
            "Yunior Ravico Caesar Putra",
            "Zaiimul Umami",
          ],
        },
        pengampu: {
          "BAHASA DAERAH|7A": "Wulan Aulia Al Azhar, S.Pd.",
          "BAHASA DAERAH|7B": "Wulan Aulia Al Azhar, S.Pd.",
          "BAHASA DAERAH|7C": "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "BAHASA DAERAH|7D": "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "BAHASA DAERAH|8A": "Jalilah Al Khasanah, S.Pd.",
          "BAHASA DAERAH|8B": "Jalilah Al Khasanah, S.Pd.",
          "BAHASA DAERAH|8C": "Jalilah Al Khasanah, S.Pd.",
          "BAHASA DAERAH|8D": "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "BAHASA DAERAH|8E": "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "BAHASA INDONESIA|7A": "Nushah Agita Widayanti, S.Pd, Gr.",
          "BAHASA INDONESIA|7B": "Nushah Agita Widayanti, S.Pd, Gr.",
          "BAHASA INDONESIA|7C": "Ferri Kurniawan, S.Pd.",
          "BAHASA INDONESIA|7D": "Ferri Kurniawan, S.Pd.",
          "BAHASA INDONESIA|8A": "Nushah Agita Widayanti, S.Pd, Gr.",
          "BAHASA INDONESIA|8B": "Nushah Agita Widayanti, S.Pd, Gr.",
          "BAHASA INDONESIA|8C": "Nushah Agita Widayanti, S.Pd, Gr.",
          "BAHASA INDONESIA|8D": "Arby Zulkifli, S.Pd, Gr.",
          "BAHASA INDONESIA|8E": "Arby Zulkifli, S.Pd, Gr.",
          "BAHASA INGGRIS|7A": "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
          "BAHASA INGGRIS|7B": "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
          "BAHASA INGGRIS|7C": "Tiagatus Luqman Widyadhana, S.Pd.",
          "BAHASA INGGRIS|7D": "Tiagatus Luqman Widyadhana, S.Pd.",
          "BAHASA INGGRIS|8A": "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
          "BAHASA INGGRIS|8B": "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
          "BAHASA INGGRIS|8C": "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
          "BAHASA INGGRIS|8D": "Tiagatus Luqman Widyadhana, S.Pd.",
          "BAHASA INGGRIS|8E": "Tiagatus Luqman Widyadhana, S.Pd.",
          "INFORMATIKA|7A": "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
          "INFORMATIKA|7B": "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
          "INFORMATIKA|7C": "Ahmad Taufiqurrohman",
          "INFORMATIKA|7D": "Ahmad Taufiqurrohman",
          "INFORMATIKA|8A": "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
          "INFORMATIKA|8B": "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
          "INFORMATIKA|8C": "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
          "INFORMATIKA|8D": "Ahmad Taufiqurrohman",
          "INFORMATIKA|8E": "Ahmad Taufiqurrohman",
          "IPA|7A": "Nur Amalia Maurie Husna, S.Pd, Gr.",
          "IPA|7B": "Nur Amalia Maurie Husna, S.Pd, Gr.",
          "IPA|7C": "Arsa Rizky Imanda, S.Pd.",
          "IPA|7D": "Arsa Rizky Imanda, S.Pd.",
          "IPA|8A": "Fitrotun Nisa, S.Pd.",
          "IPA|8B": "Nur Amalia Maurie Husna, S.Pd, Gr.",
          "IPA|8C": "Nur Amalia Maurie Husna, S.Pd, Gr.",
          "IPA|8D": "Arsa Rizky Imanda, S.Pd.",
          "IPA|8E": "Arsa Rizky Imanda, S.Pd.",
          "IPS|7A": "Rosita Eka Mardiana, S.Pd, Gr.",
          "IPS|7B": "Rosita Eka Mardiana, S.Pd, Gr.",
          "IPS|7C": "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "IPS|7D": "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "IPS|8A": "Jalilah Al Khasanah, S.Pd.",
          "IPS|8B": "Rosita Eka Mardiana, S.Pd, Gr.",
          "IPS|8C": "Rosita Eka Mardiana, S.Pd, Gr.",
          "IPS|8D": "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "IPS|8E": "Muhammad Riza Khoirul Tantomi, S.Pd.",
          "MATEMATIKA|7A": "Fitrotun Nisa, S.Pd.",
          "MATEMATIKA|7B": "Fitrotun Nisa, S.Pd.",
          "MATEMATIKA|7C": "Moreno Figo Ariyansyah Wibowo, S.Pd.",
          "MATEMATIKA|7D": "Moreno Figo Ariyansyah Wibowo, S.Pd.",
          "MATEMATIKA|8A": "Fitrotun Nisa, S.Pd.",
          "MATEMATIKA|8B": "Fitrotun Nisa, S.Pd.",
          "MATEMATIKA|8C": "Dwi Wulandari, S.Pd, Gr.",
          "MATEMATIKA|8D": "Arief Rahman Hakim, S.Pd, Gr.",
          "MATEMATIKA|8E": "Arief Rahman Hakim, S.Pd, Gr.",
          "PAI|7A": "Wulan Aulia Al Azhar, S.Pd.",
          "PAI|7B": "Wulan Aulia Al Azhar, S.Pd.",
          "PAI|7C": "Bambang Triawan Pamungkas, S.Pd.",
          "PAI|7D": "Bambang Triawan Pamungkas, S.Pd.",
          "PAI|8A": "Wulan Aulia Al Azhar, S.Pd.",
          "PAI|8B": "Wulan Aulia Al Azhar, S.Pd.",
          "PAI|8C": "Wulan Aulia Al Azhar, S.Pd.",
          "PAI|8D": "Bambang Triawan Pamungkas, S.Pd.",
          "PAI|8E": "Bambang Triawan Pamungkas, S.Pd.",
          "PJOK|7A": "Denata Novenda Afgenesya, S.Pd, Gr.",
          "PJOK|7B": "Denata Novenda Afgenesya, S.Pd, Gr.",
          "PJOK|7C": "Dany Maulana Rizky, S.Pd, Gr.",
          "PJOK|7D": "Dany Maulana Rizky, S.Pd, Gr.",
          "PJOK|8A": "Denata Novenda Afgenesya, S.Pd, Gr.",
          "PJOK|8B": "Denata Novenda Afgenesya, S.Pd, Gr.",
          "PJOK|8C": "Denata Novenda Afgenesya, S.Pd, Gr.",
          "PJOK|8D": "Dany Maulana Rizky, S.Pd, Gr.",
          "PJOK|8E": "Dany Maulana Rizky, S.Pd, Gr.",
          "PKN|7A": "Peni, S.Pd, Gr.",
          "PKN|7B": "Peni, S.Pd, Gr.",
          "PKN|7C": "Ferri Kurniawan, S.Pd.",
          "PKN|7D": "Ferri Kurniawan, S.Pd.",
          "PKN|8A": "Peni, S.Pd, Gr.",
          "PKN|8B": "Peni, S.Pd, Gr.",
          "PKN|8C": "Peni, S.Pd, Gr.",
          "PKN|8D": "Ferri Kurniawan, S.Pd.",
          "PKN|8E": "Ferri Kurniawan, S.Pd.",
          "SENI BUDAYA|7A": "Denata Novenda Afgenesya, S.Pd, Gr.",
          "SENI BUDAYA|7B": "Denata Novenda Afgenesya, S.Pd, Gr.",
          "SENI BUDAYA|7C": "Bambang Triawan Pamungkas, S.Pd.",
          "SENI BUDAYA|7D": "Bambang Triawan Pamungkas, S.Pd.",
          "SENI BUDAYA|8A": "Ummi Rihana, S.Pd.",
          "SENI BUDAYA|8B": "Ummi Rihana, S.Pd.",
          "SENI BUDAYA|8C": "Ummi Rihana, S.Pd.",
          "SENI BUDAYA|8D": "Ahmad Taufiqurrohman",
          "SENI BUDAYA|8E": "Ahmad Taufiqurrohman",
        },
      };

  const SMA_DATA = {
  "kepalaJabatan": "Kepala SMA Islam Nailul Falaah",
  "kepalaNama": "Azza Latifatus Zamairoh, S.Pd, Gr.",
  "guru": [
    "Ahmad Taufiqurrohman",
    "Ahmad Ulin Nuha, Lc.",
    "Alma Naimatul Miladiah, S.Pd, Gr.",
    "Anisatul Jannah Mulyono, S.Pd, Gr.",
    "Arby Zulkifli, S.Pd, Gr.",
    "Arief Rahman Hakim, S.Pd, Gr.",
    "Arsa Rizky Imanda, S.Pd.",
    "Azza Latifatus Zamairoh, S.Pd, Gr.",
    "Bambang Triawan Pamungkas, S.Pd.",
    "Dany Maulana Rizky, S.Pd, Gr.",
    "Denata Novenda Afgenesya, S.Pd, Gr.",
    "Dwi Wulandari, S.Pd, Gr.",
    "Ferri Kurniawan, S.Pd.",
    "Fitrotun Nisa, S.Pd.",
    "Jalilah Al Khasanah, S.Pd.",
    "Marwah Junaedi, M.Pd.",
    "Mohammad Abdul Mukhid, S.Si, Gr.",
    "Moreno Figo Ariyansyah Wibowo, S.Pd.",
    "Muhammad Riza Khairul Tantomi, S.Pd.",
    "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
    "Nur Amalia Maurie Husna, S.Pd, Gr.",
    "Nushah Agita Widayanti, S.Pd, Gr.",
    "Peni, S.Pd, Gr.",
    "Rizka Amilia Rosa S.E.",
    "Rosita Eka Mardiana, S.Pd, Gr.",
    "Tiagatus Luqman Widyadhana, S.Pd.",
    "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
    "Ummi Rihana, S.Pd.",
    "Wulan Aulia Al Azhar, S.Pd.",
    "Zihrul Fauzi, S.Pd, Gr."
  ],
  "mapel": [
    "BAHASA DAERAH",
    "BAHASA INDONESIA",
    "BAHASA INGGRIS",
    "INFORMATIKA",
    "IPA",
    "IPS",
    "MATEMATIKA",
    "PAI",
    "PJOK",
    "PKN",
    "SENI BUDAYA"
  ],
  "kelas": [
    "10A",
    "10B",
    "11A",
    "11B"
  ],
  "siswa": {
    "10A": [
      "Adibah Naylas Sifa'",
      "Amira Qotrunnada",
      "Anasya Widyawati",
      "Dhea Roikhaanah",
      "Elfina Salsabila",
      "Fauzana Alia Nafisa",
      "Khoirunnisa",
      "Kholishotun Naswa",
      "Masrifatun Qonifatur Rohma",
      "Naily Alifiatuz Zuhriyah",
      "Najwa Yasmin Wirawan",
      "Nuriyati Safrillah Amanda Syakirah",
      "Putri Dini Vatma Naysila",
      "Refaisya Elvaretta",
      "Salwa Selviya Zahrotujasmine",
      "Syariifah",
      "Thalita Eka Salsabila",
      "Zulfaa"
    ],
    "10B": [
      "Eka Putra Lukiansah",
      "Iqbal Fadilansyah",
      "Mochammad Arby Firmansyah",
      "Mohamad Zahid Hamidi",
      "Muchammad Salman Alfarisi",
      "Muh Nuril Zidan Ramadhan",
      "Muhammad Abid Fakhri",
      "Muhammad Abid Nur Hudisa",
      "Muhammad Faruq Budi Ramadhan",
      "Muhammad Rafid Nur Taslim",
      "Muhammad Suryo Ramadhan",
      "Muhammad Yusril Alfathih",
      "Okta Zahzad Awangga",
      "Pandu Abdillah",
      "Putraku Azhrael Zahro Dianto",
      "Sa'da Abdullah Asyrafal Anam"
    ],
    "11A": [
      "Aira Fawwazahana",
      "Aqila Fatimatuzzahra",
      "Auliyaul Nuril Fitriyah",
      "Azalia Muizzatin Billah Subagio",
      "Charisma Berlian Putri Medina",
      "Dayyinah",
      "Dzakiyyah",
      "Gabby Carissa Tjahjadi",
      "Hasna Ataniya Rabbani",
      "Kharisma Maulidah",
      "Nadia Khoirun Nisa'",
      "Nisa Wulandari",
      "Nurul Mutawassith Hasani",
      "Rohadatul Aiysy",
      "Roihana",
      "Salma Nur Wijayanti",
      "Syaira Halimatussa'diyah Quranina Mujit",
      "Zaimatul Ummah",
      "Zakia Firda Sari"
    ],
    "11B": [
      "Ahmad Raihan Alhamdani",
      "Chaazim",
      "Daffa Almer Dzaky",
      "Faizul Akbar Rudianzah",
      "Jahfal",
      "Jefrianto",
      "Moch. Sabilah Rossadi",
      "Mohammad Usamah Ababil",
      "Muhammad Shohafy Shifak",
      "Muhammad Syahrun Nafis Abha",
      "Sirojuddin",
      "Taufiqul Khakim",
      "Zaini Haidar Ali Yahya",
      "Zainul Abidin"
    ]
  },
  "pengampu": {
    "BAHASA DAERAH|10A": "Azza Latifatus Zamairoh, S.Pd, Gr.",
    "BAHASA DAERAH|11A": "Azza Latifatus Zamairoh, S.Pd, Gr.",
    "BAHASA DAERAH|10B": "Marwah Junaedi, M.Pd.",
    "BAHASA DAERAH|11B": "Marwah Junaedi, M.Pd.",
    "BAHASA INDONESIA|10A": "Anisatul Jannah Mulyono, S.Pd, Gr.",
    "BAHASA INDONESIA|11A": "Anisatul Jannah Mulyono, S.Pd, Gr.",
    "BAHASA INDONESIA|11B": "Arby Zulkifli, S.Pd, Gr.",
    "BAHASA INDONESIA|10B": "Zihrul Fauzi, S.Pd, Gr.",
    "BAHASA INGGRIS|10B": "Tiagatus Luqman Widyadhana, S.Pd.",
    "BAHASA INGGRIS|11B": "Tiagatus Luqman Widyadhana, S.Pd.",
    "BAHASA INGGRIS|10A": "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
    "BAHASA INGGRIS|11A": "Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.",
    "INFORMATIKA|10B": "Ahmad Taufiqurrohman",
    "INFORMATIKA|11B": "Arief Rahman Hakim, S.Pd, Gr.",
    "INFORMATIKA|10A": "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
    "INFORMATIKA|11A": "Nadiah Alma Ratnaduhita, S.Pd, Gr.",
    "IPA|11A": "Alma Naimatul Miladiah, S.Pd, Gr.",
    "IPA|10B": "Mohammad Abdul Mukhid, S.Si, Gr.",
    "IPA|11B": "Mohammad Abdul Mukhid, S.Si, Gr.",
    "IPA|10A": "Nur Amalia Maurie Husna, S.Pd, Gr.",
    "IPS|10A": "Jalilah Al Khasanah, S.Pd.",
    "IPS|11A": "Rizka Amilia Rosa S.E.",
    "IPS|10B": "Zihrul Fauzi, S.Pd, Gr.",
    "IPS|11B": "Zihrul Fauzi, S.Pd, Gr.",
    "MATEMATIKA|10A": "Dwi Wulandari, S.Pd, Gr.",
    "MATEMATIKA|11A": "Dwi Wulandari, S.Pd, Gr.",
    "MATEMATIKA|10B": "Moreno Figo Ariyansyah Wibowo, S.Pd.",
    "MATEMATIKA|11B": "Moreno Figo Ariyansyah Wibowo, S.Pd.",
    "PAI|10B": "Bambang Triawan Pamungkas, S.Pd.",
    "PAI|11B": "Bambang Triawan Pamungkas, S.Pd.",
    "PAI|10A": "Ummi Rihana, S.Pd.",
    "PAI|11A": "Ummi Rihana, S.Pd.",
    "PJOK|10B": "Dany Maulana Rizky, S.Pd, Gr.",
    "PJOK|11B": "Dany Maulana Rizky, S.Pd, Gr.",
    "PJOK|10A": "Denata Novenda Afgenesya, S.Pd, Gr.",
    "PJOK|11A": "Denata Novenda Afgenesya, S.Pd, Gr.",
    "PKN|10B": "Ferri Kurniawan, S.Pd.",
    "PKN|11B": "Ferri Kurniawan, S.Pd.",
    "PKN|10A": "Peni, S.Pd, Gr.",
    "PKN|11A": "Peni, S.Pd, Gr.",
    "SENI BUDAYA|11A": "Anisatul Jannah Mulyono, S.Pd, Gr.",
    "SENI BUDAYA|10B": "Dany Maulana Rizky, S.Pd, Gr.",
    "SENI BUDAYA|11B": "Dany Maulana Rizky, S.Pd, Gr.",
    "SENI BUDAYA|10A": "Nadiah Alma Ratnaduhita, S.Pd, Gr."
  }
};

  window.NAFA_DATA = { SMP: SMP_DATA, SMA: SMA_DATA };
  window.SMP_DATA = SMP_DATA;
  window.SMA_DATA = SMA_DATA;
})();

// Akun login awal. Untuk sistem online, akun sebenarnya dicek oleh Apps Script/Spreadsheet.
window.NAFA_ACCOUNTS = [
  {name:"Ahmad Taufiqurrohman", username:"taufiq_tik", password:"asas123", role:"guru"},
  {name:"Ahmad Ulin Nuha, Lc.", username:"ulin_pai", password:"asas123", role:"guru"},
  {name:"Alma Naimatul Miladiah, S.Pd, Gr.", username:"alma_ipa", password:"asas123", role:"guru"},
  {name:"Anisatul Jannah Mulyono, S.Pd, Gr", username:"anisatul_bin", password:"asas123", role:"guru"},
  {name:"Arby Zulkifli, S.Pd, Gr.", username:"arby_bin", password:"asas123", role:"guru"},
  {name:"Arief Rahman Hakim, S.Pd, Gr.", username:"arief_mtk", password:"asas123", role:"guru"},
  {name:"Arsa Rizky Imanda, S.Pd.", username:"arsa_ipa", password:"asas123", role:"guru"},
  {name:"Azza Latifatus Zamairoh, S.Pd, Gr.", username:"azza_bing", password:"asas123", role:"guru"},
  {name:"Bambang Triawan Pamungkas, S.Pd.", username:"bambang_pai", password:"asas123", role:"guru"},
  {name:"Dany Maulana Rizky, S.Pd, Gr.", username:"dany_pjok", password:"asas123", role:"guru"},
  {name:"Denata Novenda Afgenesya, S.Pd, Gr.", username:"dena_pjok", password:"asas123", role:"guru"},
  {name:"Dwi Wulandari, S.Pd, Gr.", username:"dwi_mtk", password:"asas123", role:"guru"},
  {name:"Ferri Kurniawan, S.Pd.", username:"ferri_pkn", password:"asas123", role:"guru"},
  {name:"Fitrotun Nisa, S.Pd.", username:"fitrotun_mtk", password:"asas123", role:"guru"},
  {name:"Jalilah Al Khasanah, S.Pd.", username:"jalilah_ips", password:"asas123", role:"guru"},
  {name:"Marwah Junaedi, M.Pd.", username:"jun_bd", password:"asas123", role:"guru"},
  {name:"Mohammad Abdul Mukhid, S.Si, Gr.", username:"mukhid_ipa", password:"asas123", role:"guru"},
  {name:"Moreno Figo Ariyansyah Wibowo, S.Pd.", username:"moreno_mtk", password:"asas123", role:"guru"},
  {name:"Muhammad Riza Khairul Tantomi, S.Pd.", username:"riza_ips", password:"asas123", role:"guru"},
  {name:"Nadiah Alma Ratnaduhita, S.Pd, Gr.", username:"nadiah_tik", password:"asas123", role:"guru"},
  {name:"Nur Amalia Maurie Husna, S.Pd, Gr.", username:"nur_ipa", password:"asas123", role:"guru"},
  {name:"Nushah Agita Widayanti, S.Pd, Gr.", username:"nushah_bin", password:"asas123", role:"guru"},
  {name:"Peni, S.Pd, Gr.", username:"peni_pkn", password:"asas123", role:"guru"},
  {name:"Rizka Amilia Rosa S.E.", username:"rizka_ips", password:"asas123", role:"guru"},
  {name:"Rosita Eka Mardiana, S.Pd, Gr.", username:"rosita_ips", password:"asas123", role:"guru"},
  {name:"Tiagatus Luqman Widyadhana, S.Pd.", username:"tiagatus_bing", password:"asas123", role:"guru"},
  {name:"Tisyrinul Awwal Fatiani, S.S, M.Pd, Gr.", username:"tisyrinul_bing", password:"asas123", role:"guru"},
  {name:"Ummi Rihana, S.Pd.", username:"ummi_pai", password:"asas123", role:"guru"},
  {name:"Wulan Aulia Al Azhar, S.Pd.", username:"wulan_pai", password:"asas123", role:"guru"},
  {name:"Zihrul Fauzi, S.Pd, Gr.", username:"zihrul_ips", password:"asas123", role:"guru"},
  {name:"ADMIN ASAS", username:"admin_asas", password:"asas2026", role:"admin"}
];
